/**
 * Sidebar structure mirrored from old_codes/views/backend/layout/sidebar.blade.php
 * and pos-api/resources/views/backend/layout/sidebar.blade.php.
 *
 * Each item uses Spatie permission names from @can() in the Blade file.
 * Paths use legacy Laravel URLs; normalizeMenuPath() maps them to React routes.
 */

const year = new Date().getFullYear();
const month = String(new Date().getMonth() + 1).padStart(2, '0');

export const SIDEBAR_MENU = [
  {
    label: 'Dashboard',
    icon: 'dripicons-meter',
    path: '/dashboard',
    controller: 'dashboard',
  },
  {
    label: 'Product',
    icon: 'dripicons-list',
    sidebarPermission: 'sidebar_product',
    children: [
      { label: 'Category', path: '/category', permission: 'categories-index', controller: 'categories' },
      { label: 'Brand', path: '/brand', permission: 'brand', controller: 'brand' },
      { label: 'Unit', path: '/unit', permission: 'unit', controller: 'unit' },
      { label: 'Product List', path: '/products', permission: 'products-index', controller: 'products' },
      { label: 'Add Product', path: '/products/create', permission: 'products-add', controller: 'products' },
      { label: 'Print Barcode', path: '/products/print_barcode', permission: 'print_barcode', controller: 'products' },
      { label: 'Adjustment List', path: '/qty_adjustment', permission: 'adjustment', controller: 'qty_adjustment' },
      { label: 'Add Adjustment', path: '/qty_adjustment/create', permission: 'adjustment', controller: 'qty_adjustment' },
      { label: 'Stock Count', path: '/stock-count', permission: 'stock_count', controller: 'stock_count' },
      { label: 'Damage List', path: '/damage-stock', permission: 'damage-stock', controller: 'damage-stock' },
    ],
  },
  {
    label: 'Purchase',
    icon: 'dripicons-card',
    sidebarPermission: 'sidebar_purchase',
    children: [
      { label: 'Purchase List', path: '/purchases', permission: 'purchases-index', controller: 'purchases' },
      { label: 'Add Purchase', path: '/purchases/create', permission: 'purchases-add', controller: 'purchases' },
      { label: 'Import Purchase By CSV', path: '/purchases/purchase_by_csv', permission: 'purchases-import', controller: 'purchases' },
      { label: 'Purchase Return', path: '/return-purchase', permission: 'purchase-return-index', controller: 'return-purchase' },
    ],
  },
  {
    label: 'Sale',
    icon: 'dripicons-cart',
    sidebarPermission: 'sidebar_sale',
    children: [
      { label: 'Sale List', path: '/sales', permission: 'sales-index', controller: 'sales' },
      { label: 'POS', path: '/pos', permission: 'sales-add', controller: 'pos' },
      { label: 'Add Sale', path: '/sales/create', permission: 'sales-add', controller: 'sales' },
      { label: 'Import Sale By CSV', path: '/sales/sale_by_csv', permission: 'sales-import', controller: 'sales' },
      { label: 'Packing Slip List', path: '/packing-slips', permission: 'packing_slip_challan', controller: 'packing_slip' },
      { label: 'Challan List', path: '/challans', permission: 'packing_slip_challan', controller: 'challan' },
      { label: 'Delivery List', path: '/delivery', permission: 'delivery', controller: 'delivery' },
      { label: 'Gift Card List', path: '/gift_cards', permission: 'gift_card', controller: 'gift_card' },
      { label: 'Coupon List', path: '/coupons', permission: 'coupon', controller: 'coupon' },
      { label: 'Courier List', path: '/couriers', controller: 'courier' },
      { label: 'Sale Return', path: '/return-sale', permission: 'returns-index', controller: 'return-sale' },
      { label: 'Sale Exchange', path: '/exchange', permission: 'exchange-index', controller: 'exchange' },
    ],
  },
  {
    label: 'Quotation',
    icon: 'dripicons-document',
    sidebarPermission: 'sidebar_quotation',
    children: [
      { label: 'Quotation List', path: '/quotations', permission: 'quotes-index', controller: 'quotations' },
      { label: 'Add Quotation', path: '/quotations/create', permission: 'quotes-add', controller: 'quotations' },
    ],
  },
  {
    label: 'Transfer',
    icon: 'dripicons-export',
    sidebarPermission: 'sidebar_transfer',
    children: [
      { label: 'Transfer List', path: '/transfers', permission: 'transfers-index', controller: 'transfers' },
      { label: 'Add Transfer', path: '/transfers/create', permission: 'transfers-add', controller: 'transfers' },
      { label: 'Import Transfer By CSV', path: '/transfers/transfer_by_csv', permission: 'transfers-import', controller: 'transfers' },
    ],
  },
  {
    label: 'Expense',
    icon: 'dripicons-wallet',
    sidebarPermission: 'sidebar_expense',
    children: [
      { label: 'Expense Category', path: '/expense_categories', permission: 'expense-categories', controller: 'expense_categories' },
      { label: 'Expense List', path: '/expenses', permission: 'expenses-index', controller: 'expenses' },
      { label: 'Add Expense', path: '/expenses', permission: 'expenses-add', controller: 'expenses' },
    ],
  },
  {
    label: 'Income',
    icon: 'dripicons-rocket',
    sidebarPermission: 'sidebar_income',
    children: [
      { label: 'Income Category', path: '/income_categories', permission: 'income-categories', controller: 'income_categories' },
      { label: 'Income List', path: '/incomes', permission: 'incomes-index', controller: 'incomes' },
      { label: 'Add Income', path: '/incomes', permission: 'incomes-add', controller: 'incomes' },
    ],
  },
  {
    label: 'Booking',
    icon: 'dripicons-calendar',
    path: '/bookings/calendar',
    permission: 'booking',
    controller: 'booking',
  },
  {
    label: 'People',
    icon: 'dripicons-user',
    sidebarPermission: 'sidebar_people',
    children: [
      { label: 'Customer List', path: '/customer', permission: 'customers-index', controller: 'customers' },
      { label: 'Supplier List', path: '/supplier', permission: 'suppliers-index', controller: 'suppliers' },
      { label: 'User List', path: '/user', permission: 'users-index', controller: 'users' },
      { label: 'Sale Agents', path: '/sale-agents', permission: 'sale-agents', controller: 'sale-agents' },
      { label: 'Biller List', path: '/biller', permission: 'billers-index', controller: 'billers' },
    ],
  },
  {
    label: 'Accounting',
    icon: 'dripicons-briefcase',
    sidebarPermission: 'sidebar_accounting',
    children: [
      { label: 'Account List', path: '/accounts', permission: 'account-index', controller: 'accounts' },
      { label: 'Add Account', path: '/accounts', permission: 'account-index', controller: 'accounts' },
      { label: 'Money Transfer', path: '/money-transfers', permission: 'money-transfer', controller: 'money-transfers' },
      { label: 'Balance Sheet', path: '/balancesheet', permission: 'balance-sheet', controller: 'balance-sheets' },
      { label: 'Account Statement', path: '/account-statement', permission: 'account-statement', controller: 'account-statements' },
    ],
  },
  {
    label: 'HRM',
    icon: 'dripicons-user-group',
    sidebarPermission: 'sidebar_hrm',
    children: [
      { label: 'Department', path: '/departments', permission: 'department', controller: 'departments' },
      { label: 'Designation', path: '/designations', permission: 'designations', controller: 'designations' },
      { label: 'Shift', path: '/shift', permission: 'shift', controller: 'shift' },
      { label: 'Employee', path: '/employees', permission: 'employees-index', controller: 'employees' },
      { label: 'Attendance', path: '/attendance', permission: 'attendance', controller: 'attendance' },
      { label: 'Holiday', path: '/holidays', permission: 'holiday', controller: 'holidays' },
      { label: 'Overtime', path: '/overtime', permission: 'overtime', controller: 'overtime' },
      { label: 'Leave Type', path: '/leave-type', permission: 'leave-type', controller: 'leave-types' },
      { label: 'Leaves', path: '/leave', permission: 'leave', controller: 'leave' },
      { label: 'Payroll', path: '/payroll', permission: 'payroll', controller: 'payroll' },
    ],
  },
  {
    label: 'Manufacturing',
    icon: 'fa fa-industry',
    moduleRequired: 'manufacturing',
    sidebarPermission: 'sidebar_manufacturing',
    children: [
      { label: 'Production List', path: '/manufacturing/productions', permission: 'production-view', controller: 'manufacturing-productions' },
      { label: 'Add Production', path: '/manufacturing/productions/create', permission: 'production-add', controller: 'manufacturing-productions' },
      { label: 'Recipe', path: '/manufacturing/recipes', permission: 'recipe-view', controller: 'manufacturing-recipes' },
      { label: 'Add Recipe', path: '/manufacturing/recipes/create', permission: 'recipe-add', controller: 'manufacturing-recipes' },
    ],
  },
  {
    label: 'WhatsApp',
    icon: 'dripicons-message',
    sidebarPermission: 'sidebar_whatsapp',
    children: [
      { label: 'WhatsApp Settings', path: '/whatsapp/settings', permission: 'sidebar_whatsapp', controller: 'whatsapp' },
      { label: 'Message Templates', path: '/whatsapp/templates', permission: 'sidebar_whatsapp', controller: 'whatsapp' },
      { label: 'Send Message', path: '/whatsapp/send', permission: 'sidebar_whatsapp', controller: 'whatsapp' },
    ],
  },
  {
    label: 'Reports',
    icon: 'dripicons-document-remove',
    sidebarPermission: 'sidebar_reports',
    children: [
      { label: 'Activity Log', path: '/setting/activity-log', permission: 'profit-loss', roleMax: 2, controller: 'reports' },
      { label: 'Profit / Loss', path: '/report/profit-loss', permission: 'profit-loss', controller: 'reports' },
      { label: 'Best Seller', path: '/report/best_seller', permission: 'best-seller', controller: 'reports' },
      { label: 'Product Report', path: '/report/product_report', permission: 'product-report', controller: 'reports' },
      { label: 'Stock Report', path: '/report/stock', permission: 'stock-report', controller: 'reports' },
      { label: 'Daily Sale', path: `/report/daily_sale/${year}/${month}`, permission: 'daily-sale', controller: 'reports' },
      { label: 'Monthly Sale', path: `/report/monthly_sale/${year}`, permission: 'monthly-sale', controller: 'reports' },
      { label: 'Daily Purchase', path: `/report/daily_purchase/${year}/${month}`, permission: 'daily-purchase', controller: 'reports' },
      { label: 'Monthly Purchase', path: `/report/monthly_purchase/${year}`, permission: 'monthly-purchase', controller: 'reports' },
      { label: 'Sale Report', path: '/report/sale_report', permission: 'sale-report', controller: 'reports' },
      { label: 'Challan Report', path: '/report/challan-report', controller: 'reports' },
      { label: 'Sale Report Chart', path: '/report/sale-report-chart', permission: 'sale-report-chart', controller: 'reports' },
      { label: 'Payment Report', path: '/report/payment_report_by_date', permission: 'payment-report', controller: 'reports' },
      { label: 'Purchase Report', path: '/report/purchase', permission: 'purchase-report', controller: 'reports' },
      { label: 'Customer Report', path: '/report/customer_report', permission: 'customer-report', controller: 'reports' },
      { label: 'Customer Group Report', path: '/report/customer-group', permission: 'customer-report', controller: 'reports' },
      { label: 'Customer Due Report', path: '/report/customer-due-report', permission: 'due-report', controller: 'reports' },
      { label: 'Supplier Report', path: '/report/supplier', permission: 'supplier-report', controller: 'reports' },
      { label: 'Supplier Due Report', path: '/report/supplier-due-report', permission: 'supplier-due-report', controller: 'reports' },
      { label: 'Warehouse Report', path: '/report/warehouse_report', permission: 'warehouse-report', controller: 'reports' },
      { label: 'Warehouse Stock Chart', path: '/report/warehouse_stock', permission: 'warehouse-stock-report', controller: 'reports' },
      { label: 'Product Expiry Report', path: '/report/product-expiry', permission: 'product-expiry-report', controller: 'reports' },
      { label: 'Product Quantity Alert', path: '/report/product_quantity_alert', permission: 'product-qty-alert', controller: 'reports' },
      { label: 'Daily Sale Objective Report', path: '/report/daily-sale-objective', permission: 'dso-report', controller: 'reports' },
      { label: 'User Report', path: '/report/user_report', permission: 'user-report', controller: 'reports' },
      { label: 'Biller Report', path: '/report/biller_report', permission: 'biller-report', controller: 'reports' },
      { label: 'Cash Register', path: '/cash-register', controller: 'cash_register' },
    ],
  },
  {
    label: 'Settings',
    icon: 'dripicons-gear',
    settingsMenu: true,
    children: [
      { label: 'Receipt Printers', path: '/printers', permission: 'role_permission', roleMax: 2, controller: 'printers' },
      { label: 'Invoice Settings', path: '/setting/invoice', permission: 'invoice_setting', controller: 'invoice_setting' },
      { label: 'Role Permission', path: '/role', permission: 'role_permission', controller: 'role' },
      { label: 'SMS Template', path: '/smstemplates', permission: 'role_permission', controller: 'smstemplates' },
      { label: 'Custom Field List', path: '/custom-fields', permission: 'custom_field', controller: 'custom-fields' },
      { label: 'Discount Plan', path: '/discount-plans', permission: 'discount_plan', controller: 'discount-plans' },
      { label: 'Discount', path: '/discounts', permission: 'discount', controller: 'discounts' },
      { label: 'All Notification', path: '/notifications', permission: 'all_notification', controller: 'notifications' },
      { label: 'Send Notification', path: '/notifications', permission: 'send_notification', controller: 'notifications' },
      { label: 'Warehouse', path: '/warehouse', permission: 'warehouse', controller: 'warehouse' },
      { label: 'Tables', path: '/tables', permission: 'role_permission', roleMax: 2, controller: 'tables' },
      { label: 'Customer Group', path: '/customer_group', permission: 'customer_group', controller: 'customer_group' },
      { label: 'Currency', path: '/currency', permission: 'currency', controller: 'currency' },
      { label: 'Tax', path: '/tax', permission: 'tax', controller: 'tax' },
      { label: 'User Profile', path: '/user-profile', controller: 'user-profile' },
      { label: 'Create SMS', path: '/setting/createsms', permission: 'create_sms', controller: 'setting' },
      { label: 'Backup Database', path: '/backup', permission: 'backup_database', controller: 'setting' },
      { label: 'General Setting', path: '/setting/general_setting', permission: 'general_setting', controller: 'general-settings' },
      { label: 'Mail Setting', path: '/setting/mail_setting', permission: 'mail_setting', controller: 'setting' },
      { label: 'Reward Point Setting', path: '/setting/reward-point-setting', permission: 'reward_point_setting', controller: 'reward-point-settings' },
      { label: 'SMS Setting', path: '/setting/sms_setting', permission: 'sms_setting', controller: 'sms-settings' },
      { label: 'Payment Gateways', path: '/setting/payment-gateways/list', permission: 'payment_gateway_setting', controller: 'setting' },
      { label: 'POS Settings', path: '/setting/pos_setting', permission: 'pos_setting', controller: 'pos-settings' },
      { label: 'POS Terminals', path: '/terminals', permission: 'terminals-index', controller: 'terminals' },
      { label: 'HRM Setting', path: '/setting/hrm_setting', permission: 'hrm_setting', controller: 'hrm-settings' },
      { label: 'Barcode Settings', path: '/barcodes', permission: 'barcode_setting', controller: 'barcode-settings' },
      { label: 'Languages', path: '/languages', permission: 'language_setting', controller: 'languages' },
    ],
  },
];
